#! /bin/bash

BIN=/usr/bin/microsoft-edge-real

# Run normally on privved containers or modified un non priv
${BIN} \
  --password-store=basic \
  --no-sandbox \
  --test-type \
  "$@" >/dev/null  2>&1
