arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description:
  A full-featured, open source, state-of-the-art video surveillance software
  system
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  DIR_IMAGES: /var/cache/zoneminder/images2
  DIR_SOUNDS: /var/cache/zoneminder/sounds2
  DZM_CONFIG_DIR: /config/addons_config/zoneminder
  ZM_DIR_EVENTS: /var/cache/zoneminder/events2
image: ghcr.io/alexbelgium/zoneminder-{arch}
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
name: Zoneminder
options:
  Images_location: /config/addons_config/zoneminder/images
ports:
  80/tcp: 3778
ports_description:
  80/tcp: web interface
schema:
  Images_location: str
services:
  - mysql:want
slug: zoneminder
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 1.36.36
webui: "[PROTO:ssl]://[HOST]:[PORT:80]/zm"
