arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description:
  Docker container running Transmission torrent client with WebUI over
  an OpenVPN tunnel
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/net/tun
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  CREATE_TUN_DEVICE: "false"
  OPENVPN_OPTS: ""
  WEBPROXY_PORT: "8118"
image: ghcr.io/alexbelgium/transmission_openvpn-{arch}
ingress: true
map:
  - config:rw
  - share:rw
  - media:rw
  - ssl
name: Transmission Openvpn
options:
  DEBUG: false
  DNS_server: 8.8.8.8,1.1.1.1
  LOCAL_NETWORK: 192.168.178.0/24
  OPENVPN_PASSWORD: pass
  OPENVPN_USERNAME: user
  PGID: "0"
  PUID: "0"
  TRANSMISSION_DOWNLOAD_DIR: /share/downloads
  TRANSMISSION_HOME: /config/addons_config/transmission
  TRANSMISSION_INCOMPLETE_DIR: /share/incomplete
  TRANSMISSION_V3_UPDATE: "true"
  TRANSMISSION_WATCH_DIR: /share/watch_dir
  TRANSMISSION_WEB_UI: flood-for-transmission
  WEBPROXY_ENABLED: "true"
panel_admin: false
panel_icon: mdi:transmission-tower
ports:
  51413/tcp: 51413
  51413/udp: 51413
  8118/tcp: 8118
  9091/tcp: 9091
ports_description:
  51413/tcp: Peer port (setup router port forwarding to this port)
  51413/udp: Peer port (setup router port forwarding to this port)
  8118/tcp: Webproxy port (optional)
  9091/tcp: Web UI port (required)
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
schema:
  DEBUG: bool
  DNS_server: str?
  LOCAL_NETWORK: str
  OPENVPN_CONFIG: str?
  OPENVPN_PASSWORD: str
  OPENVPN_PROVIDER: list(custom|anonine|anonvpn|blackvpn|btguard|bulletvpn|cryptostorm|expressvpn|fastestvpn|freevpn|froot|frostvpn|getflix|ghostpath|giganews|goosevpn|hideme|hidemyass|integrityvpn|ipvanish|ironsocket|ivacy|ivpn|mullvad|nordvpn|octanevpn|ovpn|pia|privado|privatevpn|protonvpn|proxpn|purevpn|ra4w|safervpn|slickvpn|slickvpncore|smartdnsproxy|smartvpn|surfshark|tiger|torguard|trustzone|tunnelbear|vpnac|vpnarea|vpnbook|vpnfacile|vpnht|vpntunnel|vpnunlimited|vyprvpn|wevpn|windscribe|zoogvpn)?
  OPENVPN_USERNAME: str
  PGID: int
  PUID: int
  TRANSMISSION_DOWNLOAD_DIR: str
  TRANSMISSION_HOME: str
  TRANSMISSION_INCOMPLETE_DIR: str
  TRANSMISSION_WATCH_DIR: str
  TRANSMISSION_WEB_UI: list(standard|combustion|kettu|transmission-web-control|flood-for-transmission|shift)
  WEBPROXY_ENABLED: bool
  auto_restart: bool?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  localdisks: str?
  networkdisks: str?
slug: transmission_openvpn
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: v5.3.2
