#!/bin/bash

# Use /bin/bash shebang because we don't want the container environment in here

# Version 1
# 2024-10-18 - Initial Release
WITHCONTENV_VER="1.20241018"

if [[ -f /run/s6/container_environment/UMASK ]] &&
    { [[ "$(pwdx $$)" =~ "/run/s6/legacy-services/" ]] ||
        [[ "$(pwdx $$)" =~ "/run/s6/services/" ]] ||
        [[ "$(pwdx $$)" =~ "/servicedirs/svc-" ]]; }; then
    umask "$(cat /run/s6/container_environment/UMASK)"
fi
exec /command/with-contenv "$@"
