arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description:
  High performance file syncing and sharing, with also Markdown WYSIWYG
  editing, Wiki, file label and other knowledge management features
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  NOSWAG: "1"
  PGID: "1000"
  PUID: "1000"
image: ghcr.io/alexbelgium/seafile-{arch}
map:
  - config:rw
  - share:rw
  - ssl
name: Seafile
options:
  CONFIG_LOCATION: /config/addons_config/seafile/config.yaml
  FILE_SERVER_ROOT: http://homeassistant.local:8082
  PGID: 1000
  PORT: "8082"
  PUID: 1000
  SEAFILE_ADMIN_EMAIL: me@example.com
  SEAFILE_ADMIN_PASSWORD: a_very_secret_password
  SERVER_IP: homeassistant.local
  TZ: Europe/Paris
  data_location: /share/seafile
  database: sqlite
  url: seafile.example.com
panel_admin: false
panel_icon: mdi:library
ports:
  8000/tcp: 8000
  8082/tcp: 8082
ports_description:
  8000/tcp: Seahub
  8082/tcp: File server
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
schema:
  CONFIG_LOCATION: str?
  FILE_SERVER_ROOT: str
  PGID: int
  PORT: str?
  PUID: int
  SEAFILE_ADMIN_EMAIL: email
  SEAFILE_ADMIN_PASSWORD: password
  SERVER_IP: str?
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  data_location: str
  database: list(sqlite|mariadb_addon)
  localdisks: str?
  networkdisks: str?
  url: str
services:
  - mysql:want
slug: seafile
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/seafile
version: 12.0.14
webui: http://[HOST]:[PORT:8000]
