arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description: voice communication for online gaming, education and training
environment:
  DIST_UPDATE: "0"
  INIFILE: "1"
  PGID: "503"
  PUID: "503"
  TS3SERVER_LICENSE: accept
  TS_UPDATE: "1"
image: ghcr.io/alexbelgium/teamspeak-{arch}
init: false
map:
  - share:rw
name: Teamspeak server
ports:
  10011/tcp: 10011
  30033/tcp: 30033
  41144/tcp: 41144
  9987/udp: 9987
ports_description:
  10011/tcp: ServerQuery (raw)
  30033/tcp: Filetransfer
  41144/tcp: TSDNS
  9987/udp: Voice
slug: teamspeak
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 3.13.6-8
