# GitHub Actions Path Filter Configuration
# Maps addon directory names to workflow labels
# Used by PR check workflow to detect which addons changed

# Existing addons (sample - add all from repo):
portainer: &portainer
  - added|modified: "portainer/**"

portainer_agent: &portainer_agent
  - added|modified: "portainer_agent/**"

# Add more addon labels as needed following the pattern above
