arch:
  - aarch64
  - amd64
  - armv7
codenotary: alexandrep.github@gmail.com
description:
  Inadyn is a small and simple Dynamic DNS, DDNS, client with HTTPS support.
  A large number of dynamic dns providers are supported (https://github.com/troglobit/inadyn#supported-providers).
  For those that are not, you can use a custom provider as per this project's documentation
  (https://github.com/nalipaz/hassio-addons/blob/master/README.md)
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
host_network: true
image: ghcr.io/alexbelgium/inadyn-{arch}
map:
  - ssl
name: Inadyn
options:
  providers:
    - hostname: dynamic-subdomain.example.com
      password: password
      provider: yourprovider
      username: username
schema:
  allow_ipv6: bool?
  fake_address: bool?
  forced_update: int?
  iface: str?
  iterations: int?
  period: int?
  providers:
    - append_myip: bool?
      checkip_command: str?
      checkip_path: str?
      checkip_server: str?
      checkip_ssl: bool?
      custom_provider: bool?
      ddns_path: str?
      ddns_server: str?
      hostname: str
      password: str?
      provider: str
      proxied: bool?
      ssl: bool?
      ttl: int?
      user_agent: str?
      username: str
      wildcard: bool?
  secure_ssl: bool?
  verify_address: bool?
slug: inadyn
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 2.12.0-2
