---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.1.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.1.0
codenotary:
  signer: alexandrep.github@gmail.com
