arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Mealie is a self hosted recipe manager and meal planner built in Vue
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
discovery:
  - mealie
environment:
  BASE_SUBPATH: /mealie/
  DATA_DIR: /config
  DB_ENGINE: sqlite
  MAX_WORKERS: "1"
  NUXT_APP_BASE_URL: /mealie/
  WEB_CONCURRENCY: "2"
  WEB_GUNICORN: "true"
  WORKERS_PER_CORE: "0.5"
image: ghcr.io/alexbelgium/mealie-{arch}
ingress: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - share:rw
  - ssl:rw
name: Mealie
options:
  ALLOW_SIGNUP: true
  DATA_DIR: /config
  PGID: 1000
  PUID: 1000
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_admin: false
panel_icon: mdi:silverware-fork-knife
ports:
  9001/tcp: 9090
ports_description:
  9001/tcp: Web interface
schema:
  ALLOW_SIGNUP: bool
  BASE_URL: str?
  DATA_DIR: str?
  PGID: int
  PUID: int
  certfile: str
  keyfile: str
  ssl: bool
slug: mealie
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: "v3.4.0"
