#!/usr/bin/with-contenv bash

if [ ! -d /share/plex ]; then
  echo "Creating /share/plex"
  mkdir -p /share/plex
  chown -R abc:abc /share/plex
fi

if [ ! -d /share/plex/Library ]; then
  echo "Creating /share/plex/Library"
  mkdir -p /share/plex/Library
  chown -R abc:abc /share/plex/Library
fi
