#!/usr/bin/with-contenv bash

##################
# SYMLINK CONFIG #
##################

if [ ! -d "/share/plex/Plex Media Server" ]; then
mkdir -p "/share/plex/Plex Media Server"
fi

chown -R abc:abc /share/plex
rm -r "/config/Library/Application Support/Plex Media Server"
ln -s "/share/plex/Plex Media Server" "/config/Library/Application Support"
