#!/usr/bin/with-contenv bash

##################
# SYMLINK CONFIG #
##################

if [ ! -d /share/plex ]; then
  mkdir /share/plex || true
  echo "Copying Library folder"
  mv /config/Library /share/plex
  ln -s /share/plex/Library /config
else
  chown -R abc:abc /share/plex
fi
