arch:
  - aarch64
  - amd64
audio: true
backup: cold
codenotary: alexandrep.github@gmail.com
description: Realtime acoustic bird classification system
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
image: ghcr.io/alexbelgium/birdnet-pi-{arch}
ingress: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
  - ssl
name: BirdNET-pi
options:
  BIRDSONGS_FOLDER: /config/BirdSongs
  LIVESTREAM_BOOT_ENABLED: false
  MQTT_DISABLED: true
  TZ: Europe/Paris
  Use_tphakala_model_v2: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: false
panel_admin: false
panel_icon: mdi:bird
ports:
  80/tcp: null
  8081/tcp: 8081
ports_description:
  80/tcp: "Optional : set to 80 to use caddy's automatic ssl"
  8081/tcp: Web ui
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  BIRDSONGS_FOLDER: str?
  LIVESTREAM_BOOT_ENABLED: bool
  MQTT_DISABLED: bool?
  MQTT_HOST_manual: str?
  MQTT_PASSWORD_manual: password?
  MQTT_PORT_manual: int?
  MQTT_USER_manual: str?
  TZ: str?
  Use_tphakala_model_v2: bool
  certfile: str
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  keyfile: str
  localdisks: str?
  networkdisks: str?
  pi_password: password
  ssl: bool
services:
  - mqtt:want
slug: birdnet-pi
tmpfs: true
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/birdnet-pi
usb: true
version: 2025.11.01
video: true
