#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Waiting for dbus
until [[ -e /var/run/dbus/system_bus_socket ]]; do
    sleep 1s
done
echo "Starting service: php pfm"
exec /usr/sbin/php-fpm* -F