arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: platform for accessing the audiobooks you own wherever you are
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  PGID: "0"
  PUID: "0"
image: ghcr.io/alexbelgium/calibre_web-{arch}
init: false
map:
  - share:rw
  - media:rw
name: Booksonic air
options:
  PGID: 0
  PUID: 0
ports:
  4040/tcp: 4040
ports_description:
  4040/tcp: web interface
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  PGID: int
  PUID: int
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  localdisks: str?
  networkdisks: str?
slug: booksonic-air_nas
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/booksonic_air
version: 2201.1.0
webui: http://[HOST]:[PORT:4040]
