arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Unpacks RARd files for Sonarr, Lidarr and Radarr
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  VPN_ENABLED: "false"
  VPN_PROVIDER: "null"
image: ghcr.io/alexbelgium/unpackerr-{arch}
init: false
map:
  - media:rw
  - addon_config:rw
  - homeassistant_config:rw
  - share:rw
  - ssl
name: Unpackerr
options:
  PGID: 1000
  PUID: 1000
  extraction_path: /share/downloads_packed
  watch_path: /share/downloads_unpacked
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  PGID: int
  PUID: int
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  localdisks: str?
  networkdisks: str?
slug: unpackerr
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: v0.14.5-2
