#!/usr/bin/with-contenv bash

WEBUI_PORT=${WEBUI_PORT:-8080}

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

if bashio::config.true 'openvpn_enabled'; then
    exec /usr/sbin/openvpn --config /etc/openvpn/config.ovpn --script-security 2 --up /etc/openvpn/up.sh --down /etc/openvpn/down.sh
else
    exec /usr/bin/transmission-daemon --foreground --config-dir /data/transmission
fi
