---
name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [Addon name] <title>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Addon Logs"
      description: Please paste the full log that appears when starting the addon (including banner). This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: "Architecture"
      description: What architecture are you on ?
      multiple: true
      options:
        - aarch64
        - amd64
        - armv7
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - HAos
        - Virtual Machine
    validations:
      required: false
