runOnStartup: true
cronSchedule: 0 */6 * * *
logLevel: info
webPortalConfig:
  baseUrl: https://epic.example.com
accounts:
  - email: example@gmail.com
notifiers:
  - type: email
    smtpHost: smtp.gmail.com
    smtpPort: 587
    emailSenderAddress: hello@gmail.com
    emailSenderName: Epic Games Captchas
    emailRecipientAddress: hello@gmail.com
    secure: false
    auth:
      user: hello@gmail.com
      pass: abc123
  - type: discord
    webhookUrl: https://discord.com/api/webhooks/123456789123456789/A-abcdefghijklmn-abcdefghijklmnopqrst12345678-abcdefghijklmnop123456
    mentionedUsers:
      - "914360712086843432"
    mentionedRoles:
      - "734548250895319070"
  - type: telegram
    apiUrl: https://api.telegram.org
    token: 644739147:AAGMPo-Jz3mKRnHRTnrPEDi7jUF1vqNOD5k
    chatId: "-987654321"
  - type: apprise
    apiUrl: http://192.168.1.2:8000
    urls: mailto://user:pass@gmail.com
  - type: pushover
    token: a172fyyl9gw99p2xi16tq8hnib48p2
    userKey: uvgidym7l5ggpwu2r8i1oy6diaapll
  - type: gotify
    apiUrl: https://gotify.net
    token: SnL-wAvmfo_QT
  - type: homeassistant
    instance: https://homeassistant.example.com
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    notifyservice: mobile_app_smartphone_name
  - type: bark
    key: xxxxxxxxxxxxxxxxxxxxxx
    title: epicgames-freegames
    group: epicgames-freegames
    apiUrl: https://api.day.app
  - type: ntfy
    webhookUrl: https://ntfy.example.com/mytopic
    priority: urgent
    token: tk_mytoken
