#!/usr/bin/with-contenv bash

if [ ! -d /config/jackett ]; then
  echo "Creating /config/jackett"
  mkdir -p /config/jackett
  chown -R abc:abc /config/jackett
fi

if [ ! -d /share/jackett ]; then
  echo "Creating /share/jackett"
  mkdir -p /share/jackett
  chown -R abc:abc /share/jackett
fi