arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Collabora Online office suite
environment:
  PGID: "0"
  PUID: "0"
image: ghcr.io/alexbelgium/collabora-{arch}
init: false
map:
  - addon_config:rw
  - ssl:ro
name: Collabora
options:
  aliasgroup1: ""
  certfile: fullchain.pem
  domain1: ""
  extra_params:
    --o:ssl.enable=false --o:user_interface.use_integration_theme=false
    --o:net.proto=IPv4
  keyfile: privkey.pem
  password: ""
  ssl: false
  username: ""
ports:
  9980/tcp: 9980
ports_description:
  9980/tcp: Web interface
schema:
  TZ: str?
  aliasgroup1: str
  cert_domain: bool?
  certfile: str
  dictionaries: str?
  domain1: str?
  extra_params: str?
  keyfile: str
  password: password
  server_name: str?
  ssl: bool
  username: str
slug: collabora
url: https://github.com/alexbelgium/hassio-addons
version: 25.4.6
webui: "[PROTO:ssl]://[HOST]:[PORT:9980]/browser/dist/admin/admin.html"
