---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

###############
# Rules by id #
###############
MD001: false # Heading levels should only increment by one level at a time
MD002: false # First header should be a h1 header
MD007: # Unordered list indentation
  indent: 2
MD012: false # Multiple consecutive blank lines
MD013: false # Line length
MD025: false # Multiple top level headings in the same document
MD034: false # Bare url
MD041: false # First line in file should be a top level header
MD053: false # Check links are used

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
