---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:12.2.0
  amd64: ghcr.io/hassio-addons/base/amd64:12.2.0
  armv7: ghcr.io/hassio-addons/base/armv7:12.2.0
  i386: ghcr.io/hassio-addons/base/i386:12.2.0
codenotary:
  signer: alexandrep.github@gmail.com


