#!/command/with-contenv bash
# shellcheck shell=bash

set -e

if [ ! -d "$MEILI_DIR" ]; then
  mkdir -p "$MEILI_DIR"
fi

cd "$MEILI_DIR"

exec /bin/meilisearch --no-analytics --experimental-dumpless-upgrade