#!/usr/bin/with-contenv bash

##################
# SYMLINK CONFIG #
##################

#Create folders

if [ ! -d /share/piwigo ]; then
  echo "Creating /share/piwigo"
  mkdir -p /share/piwigo
  chown -R abc:abc /share/piwigo
else
  chown -R abc:abc /share/piwigo
fi

if [ ! -d /share/piwigo/config ]; then
  echo "Creating /share/piwigo/config
  mkdir -p /share/piwigo/config
  chown -R abc:abc /share/piwigo/config
else
  chown -R abc:abc /share/piwigo/config
fi

if [ ! -d /share/piwigo/keys ]; then
  echo "Creating /share/piwigo/keys
  mkdir -p /share/piwigo/keys
  chown -R abc:abc /share/piwigo/keys
else
  chown -R abc:abc /share/piwigo/keys
fi

# Create symlinks

echo "Symlink config"
ln -s /share/piwigo/config /gallery/local || mkdir /gallery/local/config & ln -s /share/piwigo/config /gallery/local
echo "Symlink keys"
ln -s /share/piwigo/config /config/keys || mkdir /config/keys  & ln -s /share/piwigo/config /config/keys
