#!/usr/bin/with-contenv bash

##################
# SYMLINK CONFIG #
##################

# If config doesn't exist, create it
if [ ! -d /data/config ]; then
  echo "moving config folder"
  mv /gallery/local/config /data
  ln -s /data/config /gallery/local
  echo "links done"
fi

# If keys don't exist, create it
if [ ! -d /data/keys ]; then
  echo "moving keys folder"
  mv /config/keys /data
  ln -s /data/keys /config
  echo "links done"
fi
