; <?php exit; ?> DO NOT DELETE THIS LINE
lang="en-US"
dbtype="sqlite"
dbport="80"
dbuser="username"
dbpass="secret"
dbname="webtrees.sqlite"
dbhost="localhost"
tblpfx="wt_"
base_url="http://192.168.178.69:9999"
wtname="Full Name"
wtuser="username"
wtpass="mybadpassword"
wtemail="me@example.com"
rewrite_urls="0"
