#!/usr/bin/with-contenv bash

#permissions
chown abc:abc \
	/data/config/nextcloud/config \
	/data/config/nextcloud/data
chown -R abc:abc  \
	/var/lib/nginx
rm -r /data/config/www/nextcloud/assets
chmod -R 777 /data/config
