#!/usr/bin/with-contenv bash

#create folders
mkdir -p
	/share/nextcloud \
	/data/config/nextcloud/config \
	/data/config/nextcloud/data
	
#permissions
chown abc:abc
	/share/nextcloud \
	/data/config/nextcloud/config \
	/data/config/nextcloud/data
	
chown -R abc:abc  \
	/var/lib/nginx
	
rm -r /data/config/www/nextcloud/assets
chmod -R 777 /data/config
