#!/usr/bin/with-contenv bash

# copy config
[[ ! -f /data/config/www/nextcloud/config/config.php ]] && \
	cp /defaults/config.php /data/config/www/nextcloud/config/config.php

# permissions
chown abc:abc \
	/data/config/www/nextcloud/config/config.php
