arch:
  - aarch64
  - amd64
  - armv7
backup_exclude:
  - "**/cache/"
  - "**/log/"
  - "**/transcode/"
breaking_versions:
  - 10.10.6*
codenotary: alexandrep.github@gmail.com
description:
  A Free Software Media System that puts you in control of managing and
  streaming your media
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
host_dbus: true
host_network: true
image: ghcr.io/alexbelgium/jellyfin-{arch}
ingress: true
ingress_port: 0
ingress_stream: true
init: false
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
name: Jellyfin NAS
options:
  PGID: 0
  PUID: 0
  data_location: /share/jellyfin
panel_admin: false
panel_icon: mdi:billiards-rack
ports:
  1900/udp: null
  7359/udp: null
  8096/tcp: 8096
  8920/tcp: 8920
ports_description:
  1900/udp: dlna (optional)
  7359/udp: udp server discover (optional)
  8096/tcp: web interface
  8920/tcp: https web interface (optional)
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
schema:
  DOCKER_MODS: list(linuxserver/mods:jellyfin-opencl-intel|linuxserver/mods:jellyfin-amd|linuxserver/mods:jellyfin-rffmpeg|)?
  PGID: int
  PUID: int
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  data_location: str
  localdisks: str?
  networkdisks: str?
slug: jellyfin
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 10.10.7-2
video: true
