arch:
  - aarch64
  - amd64
description:
  Self-hosted, end-to-end-encrypted photo & video storage (Ente server
  + MinIO)
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  PGID: "0"
  PUID: "0"
  TZ: Europe/Paris
image: ghcr.io/alexbelgium/ente-{arch}
init: false
map:
  - addon_config:rw
name: Ente
options:
  DB_PASSWORD: ente
  DISABLE_WEB_UI: true
  ENTE_ENDPOINT_URL: http://homeassistant.local:8280
  MINIO_DATA_LOCATION: /config/minio-data
  MINIO_ROOT_PASSWORD: minioadmin
  MINIO_ROOT_USER: minioadmin
  TZ: Europe/Paris
  USE_EXTERNAL_DB: false
ports:
  3000/tcp: 8300
  3200/tcp: 8320
  8080/tcp: 8280
ports_description:
  3000/tcp: Ente web UI
  3200/tcp: MinIO S3 endpoint
  8080/tcp: Ente API (museum)
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  DB_DATABASE_NAME: str?
  DB_HOSTNAME: str?
  DB_PASSWORD: str
  DB_PORT: int?
  DB_USERNAME: str?
  DISABLE_WEB_UI: bool?
  ENTE_ENDPOINT_URL: str
  MINIO_DATA_LOCATION: str
  MINIO_ROOT_PASSWORD: str
  MINIO_ROOT_USER: str
  TZ: str?
  USE_EXTERNAL_DB: bool?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  localdisks: str?
  networkdisks: str?
slug: ente
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: "4.4.6"
video: true
webui: http://[HOST]:[PORT:3000]
