#!/usr/bin/with-contenv bash

if [ ! -d /share/storage/tv ]; then
  echo "Creating /share/storage/tv"
  mkdir -p /share/storage/tv
  chown -R abc:abc /share/storage/tv
fi

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /config/sonarr ]; then
  echo "Creating /config/sonarr"
  mkdir -p /config/sonarr
  chown -R abc:abc /config/sonarr
fi
