arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Web based comic archive browser and reader
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  CODEX_CONFIG_DIR: /config
  PGID: "0"
  PUID: "0"
hassio_api: true
homeassistant_api: true
image: ghcr.io/alexbelgium/codex-{arch}
ingress: true
ingress_stream: true
map:
  - addon_config:rw
  - media:rw
  - share:rw
name: Codex
options:
  PGID: "0"
  PUID: "0"
  csrf_allowed: http://homeassistant.local:8123,https://homeassistant.local:8123
panel_admin: false
panel_icon: mdi:book-open
ports:
  9810/tcp: 9810
ports_description:
  9810/tcp: Web UI port
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
schema:
  CODEX_RESET_ADMIN: int?
  CODEX_SKIP_INTEGRITY_CHECK: int?
  PGID: int?
  PUID: int?
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  csrf_allowed: str
  localdisks: str?
  networkdisks: str?
slug: codex
udev: true
url: https://github.com/alexbelgium/hassio-addons
version: 1.8.14
