arch:
  - aarch64
  - amd64
audio: true
codenotary: alexandrep.github@gmail.com
description: Realtime BirdNET soundscape analyzer
devices:
  - /dev/dri
  - /dev/snd
  - /dev/snd/controlC0
  - /dev/snd/controlC1
  - /dev/snd/pcmC1D0c
  - /dev/snd/pcmC1D0p
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment:
  BIRDNET_GID: "0"
  BIRDNET_UID: "0"
image: ghcr.io/alexbelgium/birdnet-go-{arch}
ingress: true
ingress_stream: true
init: false
map:
  - addon_config:rw
  - media:rw
  - share:rw
name: Birdnet-go
options:
  BIRDSONGS_FOLDER: /config/clips
  homeassistant_microphone: false
panel_admin: false
panel_icon: mdi:bird
ports:
  8080/tcp: 8080
  9090/tcp: 9090
ports_description:
  8080/tcp: Web ui
  9090/tcp: Telemetry endpoint
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - SYS_RESOURCE
schema:
  BIRDSONGS_FOLDER: str?
  TZ: str?
  cifsdomain: str?
  cifspassword: str?
  cifsusername: str?
  homeassistant_microphone: bool?
  localdisks: str?
  networkdisks: str?
services:
  - mysql:want
  - mqtt:want
slug: birdnet-go
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/birdnet-go
usb: true
version: "nightly-20251012"
