arch:
  - aarch64
  - amd64
codenotary: alexandrep.github@gmail.com
description: Fork of overseerr for jellyfin support
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n3p3
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
environment: {}
host_network: true
image: ghcr.io/alexbelgium/jellyseerr-{arch}
init: false
map:
  - config:rw
name: Jellyseerr
options:
  TYPE: emby
  TZ: Europe/Paris
ports:
  5055/tcp: 5055
ports_description:
  5055/tcp: web interface
privileged: []
schema:
  TYPE: list(emby|jellyfin)
  TZ: str?
slug: jellyseerr
udev: true
url: https://github.com/alexbelgium/hassio-addons/tree/master/jellyseerr
version: v2.7.3
webui: "[PROTO:ssl]://[HOST]:[PORT:5055]"
